apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc-dev
  labels:
    app: postgres
    env: dev
  namespace: dev
spec:
  volumeName: postgres-pv-dev
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
