apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-pvc
  labels:
    app: postgres
    env: dev
  namespace: dev
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
