apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-pv
  labels:
    app: postgres
    env: dev
spec:
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /data/postgres/dev1
